package hust.soict.hedspi.gui.javafx;

import java.io.IOException;
import java.util.ArrayList;

import javax.naming.LimitExceededException;

import hust.soict.hedspi.aims.media.Book;
import hust.soict.hedspi.aims.media.CompactDisc;
import hust.soict.hedspi.aims.media.DigitalVideoDisc;
import hust.soict.hedspi.aims.media.Media;
import hust.soict.hedspi.aims.media.Track;
import hust.soict.hedspi.aims.order.Order;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class aimsController {

	@FXML
    private TextField myTextField;
	
	private ArrayList <String> authors = new ArrayList<String>();
//	Book book2 = new Book("math","Documentory",20.5f,authors);
	private static Order newOrder;
	private int id;
	
	@FXML
    private TableView<Media> table;
	
	@FXML
    private TableColumn<Media, String> categoryColumn;

    @FXML
    private TableColumn<Media, Float> costColumn;

    @FXML
    private TableColumn<Media, Integer> idColumn;

    @FXML
    private TableColumn<Media, String> titleColumn;
    
	// Event Listener on Button.onAction
	@FXML
	public void btn0Action(ActionEvent event) {
		// TODO Autogenerated
		System.exit(0);
	}
	// Event Listener on Button.onAction
	@FXML
	public void btn1Action(ActionEvent event) throws IOException, LimitExceededException {
		// TODO Autogenerated
		newOrder = new Order();
		Parent tableViewParent = FXMLLoader.load(getClass().getResource("addOrder.fxml"));
		Scene tableViewScene = new Scene(tableViewParent);
		
		Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
		window.setScene(tableViewScene);
		window.show();
//		System.out.println(myTextField);
	}
	
	
	@FXML
	public void btnOkAction(ActionEvent event)  {
		try {
			id = Integer.parseInt(myTextField.getText());
			System.out.println(id);
			newOrder.setId(id);
			System.out.println("success");
			returnFunc(event);
		}catch(Exception e) {
			e.printStackTrace();
		}
		
	}
	
	@FXML
	public void btn2Action(ActionEvent event) throws Exception{
		Parent tableViewParent = FXMLLoader.load(getClass().getResource("case2.fxml"));
		Scene tableViewScene = new Scene(tableViewParent);
		
		Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
		window.setScene(tableViewScene);
		window.show();
	}
	
	@FXML
    public void btn4Action(ActionEvent event) throws Exception {
		FXMLLoader loader = new FXMLLoader();
		loader.setLocation(getClass().getResource("case4.fxml"));
		Parent tableViewParent = loader.load();
		Scene TableViewScene =  new Scene(tableViewParent);
		case4Controller controller = loader.getController();
		System.out.println(newOrder);
		controller.initData(newOrder);
		Stage window =  (Stage) ((Node)event.getSource()).getScene().getWindow();
		window.setScene(TableViewScene);
		window.show();
    }
	
	
	// Event Listener on Button.onAction
		@FXML
		public void btnAddBook(ActionEvent event) throws IOException {
			// TODO Autogenerated
			authors.add("sugar daddy");
			authors.add("sugar baby");
			Book book1 = new Book("hands-on","Documentory",19.65f,authors);
			newOrder.addMedia(book1);
			returnFunc(event);
		}
		// Event Listener on Button.onAction
		@FXML
		public void btnAddDigitalVideoDisc(ActionEvent event) throws IOException {
			// TODO Autogenerated
			DigitalVideoDisc dvd1 = new DigitalVideoDisc("The Lion King", "Animation", 19.95f, 87, "Roger Allers");
			newOrder.addMedia(dvd1);
			System.out.println(newOrder);
			returnFunc(event);
		}
		// Event Listener on Button.onAction
		@FXML
		public void returnFunc(ActionEvent event) throws IOException {
			Parent tableViewParent = FXMLLoader.load(getClass().getResource("aims.fxml"));
			Scene tableViewScene = new Scene(tableViewParent);
			
			Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
			window.setScene(tableViewScene);
			window.show();
		}
		public void btnReturn(ActionEvent event) throws Exception {
			// TODO Autogenerated
			returnFunc(event);
		}
		// Event Listener on Button.onAction
		@FXML
		public void btnAddCompactDisc(ActionEvent event) throws IOException {
			// TODO Autogenerated
			Track track1 = new Track("My heart", 3);
			CompactDisc compactDisc1 = new CompactDisc("Lover", "Romance", 15f, "Nghiemdz", "Taylor Swift");
			compactDisc1.addTrack(track1);
			newOrder.addMedia(compactDisc1);
			System.out.println(newOrder);
			returnFunc(event);
		}
}
