package hust.soict.hedspi.gui.javafx;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import hust.soict.hedspi.aims.media.Media;
import hust.soict.hedspi.aims.order.Order;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;

public class case4Controller  implements Initializable{
	@FXML
	private TableView<Media> table;
	@FXML
	private TableColumn<Media, String> titleColumn;
	@FXML
	private TableColumn<Media, String> categoryColumn;
	@FXML
	private TableColumn<Media, Float> costColumn;
	@FXML
	private TableColumn<Media, Integer> idColumn;

	@Override
	public void initialize(URL url, ResourceBundle rb) {
		
	}
	
	public void initData(Order order) {
//		for(Media media: order.getItemsOrdered()) {
			titleColumn.setCellValueFactory(new PropertyValueFactory<Media,String>("title"));
			categoryColumn.setCellValueFactory(new PropertyValueFactory<Media,String>("category"));
			costColumn.setCellValueFactory(new PropertyValueFactory<Media,Float>("cost"));
			idColumn.setCellValueFactory(new PropertyValueFactory<Media,Integer>("id"));
//		}
			table.setItems(getMedia(order));
	}
	
	public ObservableList<Media>getMedia(Order list){
		ObservableList<Media> order = FXCollections.observableArrayList();
		for(Media media: list.getItemsOrdered()) {
			order.add(media);
		}
		return order;
	}
	// Event Listener on Button.onAction
	@FXML
	public void returnFunc(ActionEvent event) throws IOException {
		Parent tableViewParent = FXMLLoader.load(getClass().getResource("aims.fxml"));
		Scene tableViewScene = new Scene(tableViewParent);
		
		Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
		window.setScene(tableViewScene);
		window.show();
	}
	
	@FXML
	public void btnReturn(ActionEvent event) throws Exception{
		// TODO Autogenerated
		returnFunc(event);
	}
}
