package hust.soict.hedspi.gui.javafx;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class case2Controller {

	// Event Listener on Button.onAction
	@FXML
	public void btnAddBook(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnAddDigitalVideoDisc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnReturn(ActionEvent event) throws Exception {
		// TODO Autogenerated
		Parent tableViewParent = FXMLLoader.load(getClass().getResource("aims.fxml"));
		Scene tableViewScene = new Scene(tableViewParent);
		
		Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
		window.setScene(tableViewScene);
		window.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnAddCompactDisc(ActionEvent event) {
		// TODO Autogenerated
	}
}
